url=https://store-qa.globtech.in/
browser=chrome
adminEmail=ajay@store.com
adminPassword=123456
stationaryImage=/home/docme/Downloads/download.jpeg
uniformImage=/home/docme/Downloads/download (1).jpeg
sizeChart=/home/docme/Downloads/download (2).jpeg
	