url=https://store-qa.globtech.in/
browser=chrome
adminEmail=ajay@store.com
adminPassword=123456
stationaryImage=/home/docme/Downloads/download.jpeg
uniformImage=/home/docme/Downloads/download (1).jpeg
sizeChart=/home/docme/Downloads/download (2).jpeg
orderID=2644
orderID2=2649	
exchangeID=358
returnID=18
customer=Khaleel
admissionNO=49399/22
productName=Tom & Jerry